### ISSUE TITLE
[Request] CAN Module

### ISSUE THREAD

**Issue by Jean-DrEaD** [warpme/miniarch#36]
Hi, I'm trying get Klipper/Mainsail control my printer, but can't configure CAN network(STM32F072 UCAN).

Getting this error with **modprobe**:
_modprobe: FATAL: Module can not found in directory /lib/modules/6.9.1_

I'm too n00b to know what to do, has an easy fix?
Using MiniArch-20231112-6.7.4-board-h313.x96_q_lpddr3-SD-Image

Thanks in advance!

**Comment by Jean-DrEaD** [comment]
Why completed without any info/help? :(

**Comment by warpme** [comment]
Ah sorry. I press wrong buton.
Miniarch is minimal image and generally i'm avoiding to add kernel modules per single user requests (mainly because it is hobby project of me and I have limited time for doing custom requests. sorry.)
Ideally will be when you will build yourself kernel with added can module.
